# compose file for running the database only

version: "3.7"

services:

  db:
    container_name: db
    image: postgres:13
    volumes:
      - ./docker-volumes/pgdata:/var/lib/postgresql/data:delegated
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: .env

volumes:
  pgdata: