version: "3.7"

services:

  db:
    container_name: db
    image: postgres:13
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
    ports:
      - ${POSTGRES_PORT}:5433
    env_file: .env.prod
    networks:
      - app_net

  app:
    container_name: app
    restart: always
    build: .
    env_file: .env.prod
    ports:
      - ${PORT}:${PORT}
    external_links:
      - db
    depends_on:
      - db
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net:
    driver: bridge
